development:
  adapter: postgresql
  encoding: unicode
  database: api_nasa_db
  pool: 5
  host: localhost
  username: api_nasa
  password: api_nasa

test:
  adapter: postgresql
  encoding: unicode
  database: api_nasa_db_test
  pool: 5
  username: api_nasa
  password: api_nasa

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %> 
